[[edge_functions]]
function = "registrar_nuevo_usuario"
path = "/registrar_nuevo_usuario"
method = "POST"
[[edge_functions]]
function = "realizar_nuevo_pedido"
path = "/realizar_nuevo_pedido"
method = "POST"
[[edge_functions]]
function = "eliminar_cuenta_cliente"
path = "/eliminar_cuenta_cliente"
method = "POST"